export default {
  products: [
    {
      id: '1',
      name: 'Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 59,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      id: '1',
      name: 'Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      id: '1',
      name: 'Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      id: '1',
      name: 'Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      id: '1',
      name: 'Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      id: '1',
      name: 'Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
  ],
};
