export default {
  products: [
    {
      _id: '1',
      name: 'Nike Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      _id: '1',
      name: 'Nike Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      _id: '1',
      name: 'Nike Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      _id: '1',
      name: 'Nike Shirt S Premium',
      category: 'Shirts',
      image: '/images/product-1jpg',
      price: 69,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
  ],
};
