export default {
  products: [
    {
      _id: '1',
      name: 'full Zip Runnig Shirts',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 69,
      brand: 'Hiskywin',
      rating: 4.7,
      numReviews: 10,
      contInStock: 6,
    },
    {
      _id: '2',
      name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4,
      numReviews: 7,
      contInStock: 35,
    },
    {
      _id: '3',
      name: 'Adidas Mens Long Sleeve Hoodie',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 49,
      brand: 'Adidas',
      rating: 5,
      numReviews: 80,
      contInStock: 10,
    },
    {
      _id: '4',
      name: 'Under Armour Mens Sportstyle Tricot Joogers',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 84,
      brand: 'Under Armour',
      rating: 3.2,
      numReviews: 105,
      contInStock: 9,
    },
    {
      _id: '5',
      name: 'Champion Mens Graphic Powerblend Fleence Jogger',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Champion',
      rating: 3.5,
      numReviews: 70,
      contInStock: 8,
    },
    {
      _id: '6',
      name: 'Aelfric Eden Mens Jogger Pants Long Multi-Pockets',
      category: 'Pants',
      image: '/images/product-6.jpg',
      price: 144,
      brand: 'Aelfric Eden',
      rating: 4.9,
      numReviews: 107,
      contInStock: 5,
    },
  ],
};
